# Generated by Django 4.0.4 on 2022-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_mail", "0016_mailrule_consumption_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="assign_date_from",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Use the email's date"),
                    (2, "Use attachment's parsed dates"),
                ],
                default=2,
                verbose_name="assign date from",
            ),
        ),
    ]
