# Generated by Django 4.0.4 on 2022-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_mail", "0017_mailrule_add_assign_date_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="filter_label",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
